{
 "title": "windows Node Exporter Full",
 "tags": [
  "windows",
  "agungsurya"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(windows_system_system_up_time,instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick CPU / Mem / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(windows_cpu_time_total{instance=\"$server\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{instance=\"$server\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((windows_os_physical_memory_free_bytes{instance=\"$server\"} * 100) / windows_cs_physical_memory_bytes{instance=\"$server\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((windows_os_virtual_memory_bytes{instance=\"$server\"} - windows_os_virtual_memory_free_bytes{instance=\"$server\"}) / windows_os_virtual_memory_bytes{instance=\"$server\"}) * 100\r\n\r\n"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (100 * (windows_logical_disk_free_bytes{volume=\"C:\"} / windows_logical_disk_size_bytes{volume=\"C:\"}))"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(windows_cpu_time_total{instance=\"$server\"}) by (cpu))\r\n"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_system_time_seconds{instance=\"$server\"} - windows_system_boot_time_seconds{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_paging_limit_bytes{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_size_bytes{instance=\"$server\",volume=\"C:\"}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Basic CPU / Mem / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "legendFormat": "Busy System" },
    {
     "expr": "sum by(instance) (irate(windows_cpu_time_total{instance=\"$server\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{instance=\"$server\"}[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(windows_cpu_time_total{instance=\"$server\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{instance=\"$server\"}[$__rate_interval])))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by(instance) (irate(windows_cpu_time_total{instance=\"$server\", mode=~\".*irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{instance=\"$server\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(windows_cpu_time_total{instance=\"$server\", mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{instance=\"$server\"}[$__rate_interval])))",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by(instance) (irate(windows_cpu_time_total{instance=\"$server\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(windows_cpu_time_total{instance=\"$server\"}[$__rate_interval])))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{instance=\"$server\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{instance=\"$server\"} - windows_os_physical_memory_free_bytes{instance=\"$server\"}\r\n",
     "legendFormat": "RAM Used"
    },
    { "legendFormat": "RAM Cache + Buffer" },
    {
     "expr": "windows_os_physical_memory_free_bytes{instance=\"$server\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(windows_os_virtual_memory_bytes{instance=\"$server\"} - windows_os_virtual_memory_bytes{instance=\"$server\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(windows_net_bytes_received_total{instance=\"$server\"}[$__rate_interval]) * 8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(windows_net_bytes_transmit_total{instance=\"$server\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((windows_logical_disk_free_bytes{instance=\"$server\",volume=\"C:\"} * 100) / windows_logical_disk_size_bytes{instance=\"$server\",volume=\"C:\"})\r\n",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}